#!/usr/bin/env bash
./build
if [[ "$?" -ne "0"  ]]; then
  echo "Failed to build"
else
  git add .
  git commit -am "Automatic publication commit"
  git branch -D gh-pages
  git checkout -b gh-pages
  git filter-branch --subdirectory-filter _site/ -f
  git checkout source
  git push -f --all origin
fi
